apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  storageClassName: mongodb-storage # Must match the SC defined above
  capacity:
    storage: 1Gi # Size of the local disk/partition
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # --- CRITICAL LOCAL PV FIELDS ---
  local:
    path: /mnt/mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bigdata-cluster-control-plane