apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-node0
spec:
  storageClassName: hdfs-data-storage # Must match the SC defined above
  capacity:
    storage: 1Gi # Size of the local disk/partition
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # --- CRITICAL LOCAL PV FIELDS ---
  local:
    path: /mnt/hdfs/datanode
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        # Use your custom label to target the Infra Master node
        - key: role 
          operator: In
          values:
          - hdfs-worker