apiVersion: v1
kind: PersistentVolume
metadata:
  name: datanode-pv-node0
spec:
  storageClassName: hdfs-data-storage # Must match the SC defined above
  capacity:
    storage: 1Gi # Size of the local disk/partition
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # --- Host Path Configuration ---
  hostPath:
    path: /tmp/hdfs-data
  # Removed nodeAffinity