apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datanode-pvc-node0
  namespace: hdfs
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: hdfs-data-storage  # MUST be hdfs-name-storage
  resources:
    requests:
      storage: 1Gi  # MUST be <= 1Gi