apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: hydraulic
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: hydraulic
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["create", "get", "watch", "list", "delete", "update", "patch", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
  namespace: hydraulic
subjects:
- kind: ServiceAccount
  name: spark
  namespace: hydraulic
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
