apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: kafka
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: kafka-storage  # MUST be hdfs-name-storage
  resources:
    requests:
      storage: 1Gi  # MUST be <= 1Gi